# Regression — PyCaret 4.0

Predict a continuous target. Same shape as the classification notebook, different `Experiment` subclass.

In [1]:
# PyCaret 4.0 — OOP-only engine
# https://github.com/pycaret/pycaret
import warnings
warnings.filterwarnings("ignore")
import pycaret
print("PyCaret", pycaret.__version__)

PyCaret 4.0.0.dev0

## 1. Load data

In [2]:
from pycaret.datasets import get_data
data = get_data("boston")
data.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

## 2. Fit an experiment

In [3]:
from pycaret.tasks import RegressionExperiment

exp = RegressionExperiment(target="medv", session_id=42, n_jobs=1).fit(data)
exp.X_train.shape, exp.X_test.shape

((354, 13), (152, 13))

## 3. Compare models

In [4]:
result = exp.compare_models(include=["lr", "ridge", "rf"])
result.leaderboard

Processing:   0%|          | 0/17 [00:00<?, ?it/s]

Processing:  29%|██▉       | 5/17 [00:00<00:00, 29.18it/s]

Processing:  47%|████▋     | 8/17 [00:00<00:00, 26.63it/s]

Processing:  65%|██████▍   | 11/17 [00:00<00:00, 17.85it/s]

Processing:  76%|███████▋  | 13/17 [00:03<00:01,  2.02it/s]

Processing:  88%|████████▊ | 15/17 [00:03<00:00,  2.67it/s]

Processing: 100%|██████████| 17/17 [00:04<00:00,  2.99it/s]

                         Model     MAE      MSE    RMSE      R2   RMSLE  \
rf     Random Forest Regressor  2.4842  14.3504  3.6158  0.8196  0.1543
lr           Linear Regression  3.5297  25.5507  4.9698  0.6875  0.2568
ridge         Ridge Regression  3.5162  25.7133  4.9846  0.6852  0.2596

         MAPE  TT (Sec)
rf     0.1226     0.331
lr     0.1751     0.016
ridge  0.1749     0.013

,Model,MAE,MSE,RMSE,R2,RMSLE,MAPE,TT (Sec)
rf,Random Forest Regressor,2.4842,14.3504,3.6158,0.8196,0.1543,0.1226,0.331
lr,Linear Regression,3.5297,25.5507,4.9698,0.6875,0.2568,0.1751,0.016
ridge,Ridge Regression,3.5162,25.7133,4.9846,0.6852,0.2596,0.1749,0.013

## 4. Predict on the test set

In [5]:
preds = exp.predict_model(result.best)
preds.predictions.head()

                     Model     MAE     MSE  RMSE      R2   RMSLE    MAPE
0  Random Forest Regressor  2.0714  9.2002     0  0.8765  0.1437  0.1079

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv,prediction_label
173,0.09178,0.0,4.05,0,0.510,6.416,84.099998,2.6463,5,296,16.600000,395.500000,9.04,23.600000,23.008
274,0.05644,40.0,6.41,1,0.447,6.758,32.900002,4.0776,4,254,17.600000,396.899994,3.53,32.400002,31.175
491,0.10574,0.0,27.74,0,0.609,5.983,98.800003,1.8681,4,711,20.100000,390.109985,18.07,13.600000,15.978
72,0.09164,0.0,10.81,0,0.413,6.065,7.800000,5.2873,4,305,19.200001,390.910004,5.52,22.799999,24.256
452,5.09017,0.0,18.10,0,0.713,6.297,91.800003,2.3682,24,666,20.200001,385.089996,17.27,16.100000,16.969

## 5. Persist

In [6]:
from pycaret import save_model
save_model(result.best, "artifacts/boston_regressor")

WindowsPath('C:/Users/moezs/pycaret/pycaret/artifacts/boston_regressor.pkl')