# Clustering — PyCaret 4.0

Unsupervised: no `target`, no `compare_models` / `tune_model`. You pick an algorithm with `create_model`, then call `assign_model` to label every row.

In [1]:
# PyCaret 4.0 — OOP-only engine
# https://github.com/pycaret/pycaret
import warnings
warnings.filterwarnings("ignore")
import pycaret
print("PyCaret", pycaret.__version__)

PyCaret 4.0.0.dev0

## 1. Load data

In [2]:
from pycaret.datasets import get_data
data = get_data("jewellery")
data.head()

   Age  Income  SpendingScore       Savings
0   58   77769       0.791329   6559.829923
1   59   81799       0.791082   5417.661426
2   62   74751       0.702657   9258.992965
3   59   74373       0.765680   7346.334504
4   87   17760       0.348778  16869.507130

   Age  Income  SpendingScore       Savings
0   58   77769       0.791329   6559.829923
1   59   81799       0.791082   5417.661426
2   62   74751       0.702657   9258.992965
3   59   74373       0.765680   7346.334504
4   87   17760       0.348778  16869.507130

## 2. Fit the experiment

In [3]:
from pycaret.tasks import ClusteringExperiment

exp = ClusteringExperiment(session_id=42, n_jobs=1).fit(data)
exp.X.shape

(505, 4)

## 3. Create a clustering model

`create_model` returns a `CreateResult` with the fitted `.pipeline` and CV metrics.

In [4]:
km = exp.create_model("kmeans", num_clusters=4)
km.metrics

Processing:   0%|          | 0/3 [00:00<?, ?it/s]

Processing:  67%|██████▋   | 2/3 [00:01<00:00,  1.22it/s]

   Silhouette  Calinski-Harabasz  Davies-Bouldin  Homogeneity  Rand Index  \
0      0.7207          5011.8115          0.4114            0           0

   Completeness
0             0

,Silhouette,Calinski-Harabasz,Davies-Bouldin,Homogeneity,Rand Index,Completeness
0,0.7207,5011.8115,0.4114,0,0,0

## 4. Assign cluster labels to every row

In [5]:
labelled = exp.assign_model(km.pipeline)
labelled.head()

   Age  Income  SpendingScore       Savings    Cluster
0   58   77769       0.791329   6559.830078  Cluster 0
1   59   81799       0.791082   5417.661621  Cluster 0
2   62   74751       0.702657   9258.993164  Cluster 0
3   59   74373       0.765680   7346.334473  Cluster 0
4   87   17760       0.348778  16869.507812  Cluster 2

## 5. Predict clusters on new data

In [6]:
new_data = data.sample(5, random_state=42)
exp.predict_model(km.pipeline, data=new_data).predictions

      Age    Income  SpendingScore       Savings    Cluster
173  56.0   68463.0       0.815712   8995.180088  Cluster 0
274  43.0  101641.0       0.381984  14424.097996  Cluster 3
490  84.0   36463.0       0.353621  16563.372591  Cluster 2
72   83.0   34529.0       0.317208  16517.208747  Cluster 2
305  25.0  130361.0       0.925439   4691.552139  Cluster 1